apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T13:29:52Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4109"
  uid: fb443c08-9664-4afc-8237-31f57b0da206
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.72.227
  clusterIPs:
  - 10.106.72.227
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31046
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
